// sdram_qsys.v

// Generated using ACDS version 15.0 145

`timescale 1 ps / 1 ps
module sdram_qsys (
		output wire        altpll_100k_clk,    // altpll_100k.clk
		output wire        altpll_12m_clk,     //  altpll_12m.clk
		output wire        altpll_800k_clk,    // altpll_800k.clk
		input  wire        clk_clk,            //         clk.clk
		input  wire        reset_reset_n,      //       reset.reset_n
		input  wire        reset_n_reset,      //     reset_n.reset
		output wire [12:0] sdram_addr,         //       sdram.addr
		output wire [1:0]  sdram_ba,           //            .ba
		output wire        sdram_cas_n,        //            .cas_n
		output wire        sdram_cke,          //            .cke
		output wire        sdram_cs_n,         //            .cs_n
		inout  wire [31:0] sdram_dq,           //            .dq
		output wire [3:0]  sdram_dqm,          //            .dqm
		output wire        sdram_ras_n,        //            .ras_n
		output wire        sdram_we_n,         //            .we_n
		input  wire        top_io_i_key_0,     //      top_io.i_key_0
		input  wire        top_io_i_key_1,     //            .i_key_1
		input  wire        top_io_i_key_2,     //            .i_key_2
		input  wire        top_io_i_clk_100k,  //            .i_clk_100k
		output wire        top_io_o_i2c_sclk,  //            .o_i2c_sclk
		inout  wire        top_io_io_i2c_sdat, //            .io_i2c_sdat
		input  wire        top_io_i_ps2_clk,   //            .i_ps2_clk
		input  wire        top_io_i_ps2_data,  //            .i_ps2_data
		input  wire        top_io_sample_clk,  //            .sample_clk
		input  wire        top_io_i_bclk,      //            .i_bclk
		input  wire        top_io_i_daclrck,   //            .i_daclrck
		output wire        top_io_o_aud_data   //            .o_aud_data
	);

	wire         reset_controller_0_reset_out_reset;                        // reset_controller_0:reset_out -> [Topnew_0:i_rst, mm_interconnect_0:Topnew_0_reset_reset_bridge_in_reset_reset, mm_interconnect_0:new_sdram_controller_0_reset_reset_bridge_in_reset_reset, new_sdram_controller_0:reset_n]
	wire         topnew_0_sdram_master_waitrequest;                         // mm_interconnect_0:Topnew_0_sdram_master_waitrequest -> Topnew_0:qsys_sdram_waitrequest
	wire  [31:0] topnew_0_sdram_master_readdata;                            // mm_interconnect_0:Topnew_0_sdram_master_readdata -> Topnew_0:qsys_sdram_readdata
	wire  [24:0] topnew_0_sdram_master_address;                             // Topnew_0:qsys_sdram_address -> mm_interconnect_0:Topnew_0_sdram_master_address
	wire         topnew_0_sdram_master_read;                                // Topnew_0:qsys_sdram_read -> mm_interconnect_0:Topnew_0_sdram_master_read
	wire         topnew_0_sdram_master_readdatavalid;                       // mm_interconnect_0:Topnew_0_sdram_master_readdatavalid -> Topnew_0:qsys_sdram_readdatavalid
	wire  [31:0] topnew_0_sdram_master_writedata;                           // Topnew_0:qsys_sdram_writedata -> mm_interconnect_0:Topnew_0_sdram_master_writedata
	wire         topnew_0_sdram_master_write;                               // Topnew_0:qsys_sdram_write -> mm_interconnect_0:Topnew_0_sdram_master_write
	wire         mm_interconnect_0_new_sdram_controller_0_s1_chipselect;    // mm_interconnect_0:new_sdram_controller_0_s1_chipselect -> new_sdram_controller_0:az_cs
	wire  [31:0] mm_interconnect_0_new_sdram_controller_0_s1_readdata;      // new_sdram_controller_0:za_data -> mm_interconnect_0:new_sdram_controller_0_s1_readdata
	wire         mm_interconnect_0_new_sdram_controller_0_s1_waitrequest;   // new_sdram_controller_0:za_waitrequest -> mm_interconnect_0:new_sdram_controller_0_s1_waitrequest
	wire  [24:0] mm_interconnect_0_new_sdram_controller_0_s1_address;       // mm_interconnect_0:new_sdram_controller_0_s1_address -> new_sdram_controller_0:az_addr
	wire         mm_interconnect_0_new_sdram_controller_0_s1_read;          // mm_interconnect_0:new_sdram_controller_0_s1_read -> new_sdram_controller_0:az_rd_n
	wire   [3:0] mm_interconnect_0_new_sdram_controller_0_s1_byteenable;    // mm_interconnect_0:new_sdram_controller_0_s1_byteenable -> new_sdram_controller_0:az_be_n
	wire         mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid; // new_sdram_controller_0:za_valid -> mm_interconnect_0:new_sdram_controller_0_s1_readdatavalid
	wire         mm_interconnect_0_new_sdram_controller_0_s1_write;         // mm_interconnect_0:new_sdram_controller_0_s1_write -> new_sdram_controller_0:az_wr_n
	wire  [31:0] mm_interconnect_0_new_sdram_controller_0_s1_writedata;     // mm_interconnect_0:new_sdram_controller_0_s1_writedata -> new_sdram_controller_0:az_data
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> altpll_0:reset

	Topnew #(
		.S_IDLE   (0),
		.S_NORMAL (1),
		.S_RECORD (2),
		.S_PLAY   (3)
	) topnew_0 (
		.i_clk                    (clk_clk),                             //          clk.clk
		.i_rst                    (~reset_controller_0_reset_out_reset), //        reset.reset_n
		.qsys_sdram_address       (topnew_0_sdram_master_address),       // sdram_master.address
		.qsys_sdram_writedata     (topnew_0_sdram_master_writedata),     //             .writedata
		.qsys_sdram_write         (topnew_0_sdram_master_write),         //             .write
		.qsys_sdram_read          (topnew_0_sdram_master_read),          //             .read
		.qsys_sdram_waitrequest   (topnew_0_sdram_master_waitrequest),   //             .waitrequest
		.qsys_sdram_readdata      (topnew_0_sdram_master_readdata),      //             .readdata
		.qsys_sdram_readdatavalid (topnew_0_sdram_master_readdatavalid), //             .readdatavalid
		.i_key_0                  (top_io_i_key_0),                      //       ext_io.i_key_0
		.i_key_1                  (top_io_i_key_1),                      //             .i_key_1
		.i_key_2                  (top_io_i_key_2),                      //             .i_key_2
		.i_clk_100k               (top_io_i_clk_100k),                   //             .i_clk_100k
		.o_i2c_sclk               (top_io_o_i2c_sclk),                   //             .o_i2c_sclk
		.io_i2c_sdat              (top_io_io_i2c_sdat),                  //             .io_i2c_sdat
		.i_ps2_clk                (top_io_i_ps2_clk),                    //             .i_ps2_clk
		.i_ps2_data               (top_io_i_ps2_data),                   //             .i_ps2_data
		.sample_clk               (top_io_sample_clk),                   //             .sample_clk
		.i_bclk                   (top_io_i_bclk),                       //             .i_bclk
		.i_daclrck                (top_io_i_daclrck),                    //             .i_daclrck
		.o_aud_data               (top_io_o_aud_data)                    //             .o_aud_data
	);

	sdram_qsys_altpll_0 altpll_0 (
		.clk       (clk_clk),                        //       inclk_interface.clk
		.reset     (rst_controller_reset_out_reset), // inclk_interface_reset.reset
		.read      (),                               //             pll_slave.read
		.write     (),                               //                      .write
		.address   (),                               //                      .address
		.readdata  (),                               //                      .readdata
		.writedata (),                               //                      .writedata
		.c0        (altpll_12m_clk),                 //                    c0.clk
		.c1        (altpll_100k_clk),                //                    c1.clk
		.c2        (altpll_800k_clk),                //                    c2.clk
		.areset    (),                               //        areset_conduit.export
		.locked    (),                               //        locked_conduit.export
		.phasedone ()                                //     phasedone_conduit.export
	);

	sdram_qsys_new_sdram_controller_0 new_sdram_controller_0 (
		.clk            (clk_clk),                                                   //   clk.clk
		.reset_n        (~reset_controller_0_reset_out_reset),                       // reset.reset_n
		.az_addr        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_new_sdram_controller_0_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_new_sdram_controller_0_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_new_sdram_controller_0_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_new_sdram_controller_0_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_addr),                                                //  wire.export
		.zs_ba          (sdram_ba),                                                  //      .export
		.zs_cas_n       (sdram_cas_n),                                               //      .export
		.zs_cke         (sdram_cke),                                                 //      .export
		.zs_cs_n        (sdram_cs_n),                                                //      .export
		.zs_dq          (sdram_dq),                                                  //      .export
		.zs_dqm         (sdram_dqm),                                                 //      .export
		.zs_ras_n       (sdram_ras_n),                                               //      .export
		.zs_we_n        (sdram_we_n)                                                 //      .export
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) reset_controller_0 (
		.reset_in0      (reset_n_reset),                      // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (reset_controller_0_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	sdram_qsys_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                            (clk_clk),                                                   //                                          clk_0_clk.clk
		.new_sdram_controller_0_reset_reset_bridge_in_reset_reset (reset_controller_0_reset_out_reset),                        // new_sdram_controller_0_reset_reset_bridge_in_reset.reset
		.Topnew_0_reset_reset_bridge_in_reset_reset               (reset_controller_0_reset_out_reset),                        //               Topnew_0_reset_reset_bridge_in_reset.reset
		.Topnew_0_sdram_master_address                            (topnew_0_sdram_master_address),                             //                              Topnew_0_sdram_master.address
		.Topnew_0_sdram_master_waitrequest                        (topnew_0_sdram_master_waitrequest),                         //                                                   .waitrequest
		.Topnew_0_sdram_master_read                               (topnew_0_sdram_master_read),                                //                                                   .read
		.Topnew_0_sdram_master_readdata                           (topnew_0_sdram_master_readdata),                            //                                                   .readdata
		.Topnew_0_sdram_master_readdatavalid                      (topnew_0_sdram_master_readdatavalid),                       //                                                   .readdatavalid
		.Topnew_0_sdram_master_write                              (topnew_0_sdram_master_write),                               //                                                   .write
		.Topnew_0_sdram_master_writedata                          (topnew_0_sdram_master_writedata),                           //                                                   .writedata
		.new_sdram_controller_0_s1_address                        (mm_interconnect_0_new_sdram_controller_0_s1_address),       //                          new_sdram_controller_0_s1.address
		.new_sdram_controller_0_s1_write                          (mm_interconnect_0_new_sdram_controller_0_s1_write),         //                                                   .write
		.new_sdram_controller_0_s1_read                           (mm_interconnect_0_new_sdram_controller_0_s1_read),          //                                                   .read
		.new_sdram_controller_0_s1_readdata                       (mm_interconnect_0_new_sdram_controller_0_s1_readdata),      //                                                   .readdata
		.new_sdram_controller_0_s1_writedata                      (mm_interconnect_0_new_sdram_controller_0_s1_writedata),     //                                                   .writedata
		.new_sdram_controller_0_s1_byteenable                     (mm_interconnect_0_new_sdram_controller_0_s1_byteenable),    //                                                   .byteenable
		.new_sdram_controller_0_s1_readdatavalid                  (mm_interconnect_0_new_sdram_controller_0_s1_readdatavalid), //                                                   .readdatavalid
		.new_sdram_controller_0_s1_waitrequest                    (mm_interconnect_0_new_sdram_controller_0_s1_waitrequest),   //                                                   .waitrequest
		.new_sdram_controller_0_s1_chipselect                     (mm_interconnect_0_new_sdram_controller_0_s1_chipselect)     //                                                   .chipselect
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                 // reset_in0.reset
		.clk            (clk_clk),                        //       clk.clk
		.reset_out      (rst_controller_reset_out_reset), // reset_out.reset
		.reset_req      (),                               // (terminated)
		.reset_req_in0  (1'b0),                           // (terminated)
		.reset_in1      (1'b0),                           // (terminated)
		.reset_req_in1  (1'b0),                           // (terminated)
		.reset_in2      (1'b0),                           // (terminated)
		.reset_req_in2  (1'b0),                           // (terminated)
		.reset_in3      (1'b0),                           // (terminated)
		.reset_req_in3  (1'b0),                           // (terminated)
		.reset_in4      (1'b0),                           // (terminated)
		.reset_req_in4  (1'b0),                           // (terminated)
		.reset_in5      (1'b0),                           // (terminated)
		.reset_req_in5  (1'b0),                           // (terminated)
		.reset_in6      (1'b0),                           // (terminated)
		.reset_req_in6  (1'b0),                           // (terminated)
		.reset_in7      (1'b0),                           // (terminated)
		.reset_req_in7  (1'b0),                           // (terminated)
		.reset_in8      (1'b0),                           // (terminated)
		.reset_req_in8  (1'b0),                           // (terminated)
		.reset_in9      (1'b0),                           // (terminated)
		.reset_req_in9  (1'b0),                           // (terminated)
		.reset_in10     (1'b0),                           // (terminated)
		.reset_req_in10 (1'b0),                           // (terminated)
		.reset_in11     (1'b0),                           // (terminated)
		.reset_req_in11 (1'b0),                           // (terminated)
		.reset_in12     (1'b0),                           // (terminated)
		.reset_req_in12 (1'b0),                           // (terminated)
		.reset_in13     (1'b0),                           // (terminated)
		.reset_req_in13 (1'b0),                           // (terminated)
		.reset_in14     (1'b0),                           // (terminated)
		.reset_req_in14 (1'b0),                           // (terminated)
		.reset_in15     (1'b0),                           // (terminated)
		.reset_req_in15 (1'b0)                            // (terminated)
	);

endmodule
